# p2p-observer example config file

# Bitcoin network to connect to.
# Options: mainnet, signet, testnet4, testnet3, regtest
network: signet

# How often to send a ping to connected peers, in seconds.
ping_interval_secs: 120

# How many new connection tasks should be spawned per second.
connections_per_second: 1

# Initial bootstrap peers to connect to.
# These are used to:
# - Sync headers from in an initial boostrap phase. If you can't connect to
#   them, you can't sync the headers.
# - Learn about new peer addresses via GETADDR.
# One or two semi-trusted boostrap nodes should be enough.
bootstrap_addrs:
  - "1.2.3.4:38333"
  - "5.6.7.8:38333"

# NATS server URL for publishing events.
nats_url: "nats://localhost:4222"

# Which network types to connect to.
# IPv4 is enabled by default. All others must be explicitly enabled.
networks:
  ipv4:
    enabled: true
  ipv6:
    enabled: false
  tor:
    enabled: false
    # Address of the local Tor SOCKS5 proxy.
    proxy_addr: "127.0.0.1:9050"
  cjdns:
    enabled: false
  i2p:
    enabled: false

# Log level per target. Options: error, warn, info, debug, trace
log_levels:
  main: debug
  connection: info
  protocol: debug
  addresses: debug
  publisher: info
  rpc: info
  headertree: info
