# p2p-observer example config file

# Bitcoin network to connect to.
# Options: mainnet, signet, testnet4, testnet3, regtest
network: signet

# How often to send a ping to connected peers, in seconds.
ping_interval_secs: 120

# How many new connection tasks should be spawned per second.
connections_per_second: 1

# Initial peers to connect to. The observer will discover more via ADDR/ADDRV2
# messages and does not need many bootstrap addresses to get started.
bootstrap_addrs:
  - "1.2.3.4:38333"
  - "5.6.7.8:38333"

# NATS server URL for publishing events.
nats_url: "nats://localhost:4222"

# Log level per target. Options: error, warn, info, debug, trace
log_levels:
  main: debug
  connection: info
  protocol: debug
  addresses: debug
  publisher: info
  rpc: info
